# Welcome to Jekyll!

# Website settings
title: WB Analytics
description: WB Analytics career website
keywords: 
baseurl:  / # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://wbanalytics.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/recent-updates  # url should be '/homepage/static/assets/img/recent-updates' as before

# author -- index page "about" section
author:  # change following line to your infomation.
  name: WB Analytics  # Be used at recent supdates posts' author.
  first_name: WB  # Be used at index page about section.
  last_name: Analytics  # Be used at index page about section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: wbanalytics  # Leave blank if you don't have now
  linkedin_id: wb-games # Leave blank if you don't have now
  facebook_username: WBCareers # Leave blank if you don't have now
  twitter_username:  WBCareers # Leave blank if you don't have now
  email: mhowell@wbgames.com  # Leave blank if you don't have now
  cv:  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  #desc: 

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
# name: jalpc

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-135039915-3

## google optimize
go:
#   id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## carousels
index_carousel: on  # index page carousel switch
recent_updates_carousel: on  # updates page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

